name-template: "v$RESOLVED_VERSION for window x64"
tag-template: "v$RESOLVED_VERSION-window"

template: |
  ## Electron.js 로 개발한 매크로 프로젝트입니다. - for window x64

  > 매크로를 통해 웹 서핑 시 사용자의 불편함을 줄이고
  > 매크로를 사용한다고 해도 기존 브라우저를 사용하는 것처럼 느낄 수 있도록 하기 위해 집중했습니다.
  > - 수동기록을 통해 사용자가 직접 시작 시점과 종료 시점을 정해 매크로를 기록할 수 있습니다.

  ### [변경 사항]
  $CHANGES

  ### [기능]
  - 매크로 기록
  - 매크로 북마크 모아보기
  - 매크로 수정 및 삭제
  - 매크로 단축키 설정
  - 매크로 실행

  ### [사용 툴]
  - Electron.js
  - Vite
  - React.js
  - Zustand
  - Tailwind.css

  **Full Changelog**: https://github.com/soobolee/auto-page/compare/v$PREVIOUS_TAG...v$NEXT_TAG

change-template: "- $TITLE (#$NUMBER)"

version-resolver:
  major:
    labels:
      - "major"
  minor:
    labels:
      - "minor"
  patch:
    labels:
      - "patch"
  default: patch
  commit-message:
    major: '^BREAKING CHANGE:'
    minor: '^feat:'
    patch: '^fix:|^test:|^design:|^build:|^refactor:'
